### ISSUE TITLE
cli doesn't finds the module

### ISSUE THREAD

**Issue by Nama** [SubhrajitPrusty/wallgen#68]
**Describe the bug**
Installing in a venv and running `wallgen` errors like this:
```
$ wallgen
Traceback (most recent call last):
  File "/home/yama/venv/wallgen/bin/wallgen", line 5, in <module>
    from wallgen import cli
ModuleNotFoundError: No module named 'wallgen'
```
**Desktop (please complete the following information):**
 - 6.5.9-zen2-1-zen
 - Arch Linux
 - Python 3.11.5

**Workaround**
`python -m wallgen pic shape ...`

**Comment by SubhrajitPrusty** [comment]
Seems like you are using a virtualenv to install the package. You would need to add the path to `PATH` for the cli to work. [ref](https://stackoverflow.com/questions/26071059/virtualenv-and-cli-tools)

**Comment by Nama** [comment]
But the venv is active...

```
$ wallgen
bash: wallgen: command not found
$ source venv/wallgen/bin/activate
$ wallgen
Traceback (most recent call last):
  File "/home/yama/venv/wallgen/bin/wallgen", line 5, in <module>
    from wallgen import cli
ModuleNotFoundError: No module named 'wallgen'
$ which wallgen
/home/yama/venv/wallgen/bin/wallgen
```

**Comment by SubhrajitPrusty** [comment]
I cannot reproduce this. Can you try installing the module without `--editable` flag?

**Comment by Nama** [comment]
Same error.
Idk, if nobody else is having this issue, must be me. And I'm fine with using `python -m wallgen ...`.

One thing I noticed, is that your module is in the root of the repository. And after checking my venv, I noticed that all modules have two folders in `lib/python3.11/site-packages/`:
```
...
click
click-8.1.7.dist-info
...
```
wallgen only has one folder: `wallgen-1.0.dist-info`
All the files which should be in the `wallgen` folder are in the `tools` folder.

You might consider putting everything in a subfolder.

You can close this if you don't want to investigate any further.
