### ISSUE TITLE
Missing -p parameter isn't handled

### ISSUE THREAD

**Issue by Nama** [SubhrajitPrusty/wallgen#69]
**Describe the bug**
Missing `-p` results in a traceback instead of an error. Adding `-p` to the same command works as expected. It complained successfully when `-t` was missing.
There's also no indication that `-p` is required.

```
$ python -m wallgen pic shape -t tri /home/yama/Pictures/uwqhd/tree_colors.jpg
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/yama/Downloads/wallgen/wallgen.py", line 799, in <module>
    cli()
  File "/home/yama/venv/wallgen/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yama/venv/wallgen/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/yama/venv/wallgen/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yama/venv/wallgen/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yama/venv/wallgen/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yama/venv/wallgen/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yama/Downloads/wallgen/wallgen.py", line 672, in pic_shape
    img = genTriangle(width, height, img, outline, pic=True, per=percent)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yama/Downloads/wallgen/tools/shapes.py", line 333, in genTriangle
    per = per / 5  # more percentage is too small
          ~~~~^~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Desktop (please complete the following information):**
- 6.5.9-zen2-1-zen
- Arch Linux
- Python 3.11.5

**Comment by SubhrajitPrusty** [comment]
fixed by 323ddb6f16e1bd3afb355d979565d0bf34a4b7ac
